---
# External Secret for Application-level secrets (JWT, encryption keys, etc.)
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: application-secrets
  namespace: link-services
  labels:
    app: link-platform
    component: application-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: link-secret-store
    kind: SecretStore
  target:
    name: application-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        # Authentication secrets
        JWT_SECRET: "{{ .jwtSecret }}"
        SERVICE_AUTH_TOKEN: "{{ .serviceAuthToken }}"
        # Encryption secrets
        DATA_ENCRYPTION_KEY: "{{ .dataEncryptionKey }}"
        DATA_ENCRYPTION_VERSION: "{{ .dataEncryptionVersion }}"
        DATA_ENCRYPTION_LEGACY_KEYS: "{{ .dataEncryptionLegacyKeys }}"
  data:
    - secretKey: jwtSecret
      remoteRef:
        key: "link-app/application"
        property: "jwt_secret"
    - secretKey: serviceAuthToken
      remoteRef:
        key: "link-app/application"
        property: "service_auth_token"
    - secretKey: dataEncryptionKey
      remoteRef:
        key: "link-app/application"
        property: "data_encryption_key"
    - secretKey: dataEncryptionVersion
      remoteRef:
        key: "link-app/application"
        property: "data_encryption_version"
    - secretKey: dataEncryptionLegacyKeys
      remoteRef:
        key: "link-app/application"
        property: "data_encryption_legacy_keys"

---
# External Secret for Third-party API keys
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-keys
  namespace: link-services
  labels:
    app: link-platform
    component: api-keys
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: link-secret-store
    kind: SecretStore
  target:
    name: api-keys
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        OPENAI_API_KEY: "{{ .openaiApiKey }}"
        QDRANT_API_KEY: "{{ .qdrantApiKey }}"
  data:
    - secretKey: openaiApiKey
      remoteRef:
        key: "link-app/api-keys"
        property: "openai_api_key"
    - secretKey: qdrantApiKey
      remoteRef:
        key: "link-app/api-keys"
        property: "qdrant_api_key"