---
# External Secret for Sentry Configuration
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sentry-config
  namespace: link-services
  labels:
    app: sentry
    component: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: link-secret-store
    kind: SecretStore
  target:
    name: sentry-config
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        # Backend Sentry DSN
        backend-dsn: "{{ .backendDsn }}"
        # Frontend Sentry DSN
        frontend-dsn: "{{ .frontendDsn }}"
        # Sentry environment
        environment: "{{ .environment }}"
        # Sentry organization
        organization: "{{ .organization }}"
        # Sentry project slugs
        backend-project: "{{ .backendProject }}"
        frontend-project: "{{ .frontendProject }}"
        # Release version (will be set by CI/CD)
        release: "{{ .release | default \"unknown\" }}"
        # Auth token for releases
        auth-token: "{{ .authToken }}"
  data:
    - secretKey: backendDsn
      remoteRef:
        key: "link-app/observability/sentry"
        property: "backend_dsn"
    - secretKey: frontendDsn
      remoteRef:
        key: "link-app/observability/sentry"
        property: "frontend_dsn"
    - secretKey: environment
      remoteRef:
        key: "link-app/observability/sentry"
        property: "environment"
    - secretKey: organization
      remoteRef:
        key: "link-app/observability/sentry"
        property: "organization"
    - secretKey: backendProject
      remoteRef:
        key: "link-app/observability/sentry"
        property: "backend_project"
    - secretKey: frontendProject
      remoteRef:
        key: "link-app/observability/sentry"
        property: "frontend_project"
    - secretKey: release
      remoteRef:
        key: "link-app/observability/sentry"
        property: "release"
    - secretKey: authToken
      remoteRef:
        key: "link-app/observability/sentry"
        property: "auth_token"