auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: info

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

limits_config:
  retention_period: 720h # 30 days for production
  max_query_series: 1000
  max_query_parallelism: 32
  max_concurrent_tail_requests: 20
  max_cache_freshness_per_query: 10m
  split_queries_by_interval: 15m

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 500
  cache_results: true
  max_retries: 5

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://alertmanager:9093
  enable_alertmanager_v2: true

# Production-specific table manager for index lifecycle management
table_manager:
  retention_deletes_enabled: true
  retention_period: 720h

analytics:
  reporting_enabled: false

# Performance optimizations for production
ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 30m
  chunk_block_size: 262144
  chunk_encoding: snappy
  max_chunk_age: 1h

compactor:
  working_directory: /loki/compactor
  shared_store: filesystem