// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/search/search_service.proto

package search

import (
	common "github.com/link-app/backend/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Search scope enum
type SearchScope int32

const (
	SearchScope_ALL_USERS SearchScope = 0
	SearchScope_FRIENDS   SearchScope = 1
	SearchScope_DISCOVERY SearchScope = 2
	SearchScope_NEARBY    SearchScope = 3
)

// Enum value maps for SearchScope.
var (
	SearchScope_name = map[int32]string{
		0: "ALL_USERS",
		1: "FRIENDS",
		2: "DISCOVERY",
		3: "NEARBY",
	}
	SearchScope_value = map[string]int32{
		"ALL_USERS": 0,
		"FRIENDS":   1,
		"DISCOVERY": 2,
		"NEARBY":    3,
	}
)

func (x SearchScope) Enum() *SearchScope {
	p := new(SearchScope)
	*p = x
	return p
}

func (x SearchScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchScope) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_search_search_service_proto_enumTypes[0].Descriptor()
}

func (SearchScope) Type() protoreflect.EnumType {
	return &file_proto_search_search_service_proto_enumTypes[0]
}

func (x SearchScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchScope.Descriptor instead.
func (SearchScope) EnumDescriptor() ([]byte, []int) {
	return file_proto_search_search_service_proto_rawDescGZIP(), []int{0}
}

type ReindexStatus int32

const (
	ReindexStatus_PENDING   ReindexStatus = 0
	ReindexStatus_RUNNING   ReindexStatus = 1
	ReindexStatus_COMPLETED ReindexStatus = 2
	ReindexStatus_FAILED    ReindexStatus = 3
	ReindexStatus_CANCELLED ReindexStatus = 4
)

// Enum value maps for ReindexStatus.
var (
	ReindexStatus_name = map[int32]string{
		0: "PENDING",
		1: "RUNNING",
		2: "COMPLETED",
		3: "FAILED",
		4: "CANCELLED",
	}
	ReindexStatus_value = map[string]int32{
		"PENDING":   0,
		"RUNNING":   1,
		"COMPLETED": 2,
		"FAILED":    3,
		"CANCELLED": 4,
	}
)

func (x ReindexStatus) Enum() *ReindexStatus {
	p := new(ReindexStatus)
	*p = x
	return p
}

func (x ReindexStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReindexStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_search_search_service_proto_enumTypes[1].Descriptor()
}

func (ReindexStatus) Type() protoreflect.EnumType {
	return &file_proto_search_search_service_proto_enumTypes[1]
}

func (x ReindexStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReindexStatus.Descriptor instead.
func (ReindexStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_search_search_service_proto_rawDescGZIP(), []int{1}
}

// Search request message
type SearchRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Query            string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit            int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	UserIds          []*common.UUID         `protobuf:"bytes,3,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	ExcludeUserId    *common.UUID           `protobuf:"bytes,4,opt,name=exclude_user_id,json=excludeUserId,proto3" json:"exclude_user_id,omitempty"`
	Scope            SearchScope            `protobuf:"varint,5,opt,name=scope,proto3,enum=search.SearchScope" json:"scope,omitempty"`
	RequestingUserId *common.UUID           `protobuf:"bytes,6,opt,name=requesting_user_id,json=requestingUserId,proto3" json:"requesting_user_id,omitempty"`
	CenterLocation   *Location              `protobuf:"bytes,7,opt,name=center_location,json=centerLocation,proto3" json:"center_location,omitempty"`
	MaxDistanceKm    float64                `protobuf:"fixed64,8,opt,name=max_distance_km,json=maxDistanceKm,proto3" json:"max_distance_km,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_proto_search_search_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_search_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_search_service_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchRequest) GetUserIds() []*common.UUID {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *SearchRequest) GetExcludeUserId() *common.UUID {
	if x != nil {
		return x.ExcludeUserId
	}
	return nil
}

func (x *SearchRequest) GetScope() SearchScope {
	if x != nil {
		return x.Scope
	}
	return SearchScope_ALL_USERS
}

func (x *SearchRequest) GetRequestingUserId() *common.UUID {
	if x != nil {
		return x.RequestingUserId
	}
	return nil
}

func (x *SearchRequest) GetCenterLocation() *Location {
	if x != nil {
		return x.CenterLocation
	}
	return nil
}

func (x *SearchRequest) GetMaxDistanceKm() float64 {
	if x != nil {
		return x.MaxDistanceKm
	}
	return 0
}

// Location for proximity search
type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Accuracy      float64                `protobuf:"fixed64,3,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_proto_search_search_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_search_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_proto_search_search_service_proto_rawDescGZIP(), []int{1}
}

func (x *Location) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Location) GetAccuracy() float64 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

// Search response message
type SearchResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Results         []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	QueryProcessed  string                 `protobuf:"bytes,2,opt,name=query_processed,json=queryProcessed,proto3" json:"query_processed,omitempty"`
	TotalCandidates int32                  `protobuf:"varint,3,opt,name=total_candidates,json=totalCandidates,proto3" json:"total_candidates,omitempty"`
	SearchTimeMs    int32                  `protobuf:"varint,4,opt,name=search_time_ms,json=searchTimeMs,proto3" json:"search_time_ms,omitempty"`
	Metadata        *SearchMetadata        `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_proto_search_search_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_search_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_search_service_proto_rawDescGZIP(), []int{2}
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchResponse) GetQueryProcessed() string {
	if x != nil {
		return x.QueryProcessed
	}
	return ""
}

func (x *SearchResponse) GetTotalCandidates() int32 {
	if x != nil {
		return x.TotalCandidates
	}
	return 0
}

func (x *SearchResponse) GetSearchTimeMs() int32 {
	if x != nil {
		return x.SearchTimeMs
	}
	return 0
}

func (x *SearchResponse) GetMetadata() *SearchMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Search metadata
type SearchMetadata struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ScopeUsed          SearchScope            `protobuf:"varint,1,opt,name=scope_used,json=scopeUsed,proto3,enum=search.SearchScope" json:"scope_used,omitempty"`
	EmbeddingGenerated bool                   `protobuf:"varint,2,opt,name=embedding_generated,json=embeddingGenerated,proto3" json:"embedding_generated,omitempty"`
	EmbeddingModel     string                 `protobuf:"bytes,3,opt,name=embedding_model,json=embeddingModel,proto3" json:"embedding_model,omitempty"`
	VectorDimension    int32                  `protobuf:"varint,4,opt,name=vector_dimension,json=vectorDimension,proto3" json:"vector_dimension,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SearchMetadata) Reset() {
	*x = SearchMetadata{}
	mi := &file_proto_search_search_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMetadata) ProtoMessage() {}

func (x *SearchMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_search_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMetadata.ProtoReflect.Descriptor instead.
func (*SearchMetadata) Descriptor() ([]byte, []int) {
	return file_proto_search_search_service_proto_rawDescGZIP(), []int{3}
}

func (x *SearchMetadata) GetScopeUsed() SearchScope {
	if x != nil {
		return x.ScopeUsed
	}
	return SearchScope_ALL_USERS
}

func (x *SearchMetadata) GetEmbeddingGenerated() bool {
	if x != nil {
		return x.EmbeddingGenerated
	}
	return false
}

func (x *SearchMetadata) GetEmbeddingModel() string {
	if x != nil {
		return x.EmbeddingModel
	}
	return ""
}

func (x *SearchMetadata) GetVectorDimension() int32 {
	if x != nil {
		return x.VectorDimension
	}
	return 0
}

// Individual search result
type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *common.UUID           `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	MatchReasons  []string               `protobuf:"bytes,3,rep,name=match_reasons,json=matchReasons,proto3" json:"match_reasons,omitempty"`
	MatchMetadata *MatchMetadata         `protobuf:"bytes,4,opt,name=match_metadata,json=matchMetadata,proto3" json:"match_metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_proto_search_search_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_search_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_proto_search_search_service_proto_rawDescGZIP(), []int{4}
}

func (x *SearchResult) GetUserId() *common.UUID {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *SearchResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SearchResult) GetMatchReasons() []string {
	if x != nil {
		return x.MatchReasons
	}
	return nil
}

func (x *SearchResult) GetMatchMetadata() *MatchMetadata {
	if x != nil {
		return x.MatchMetadata
	}
	return nil
}

// Match metadata
type MatchMetadata struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MatchedKeywords    []string               `protobuf:"bytes,1,rep,name=matched_keywords,json=matchedKeywords,proto3" json:"matched_keywords,omitempty"`
	SemanticSimilarity float32                `protobuf:"fixed32,2,opt,name=semantic_similarity,json=semanticSimilarity,proto3" json:"semantic_similarity,omitempty"`
	KeywordSimilarity  float32                `protobuf:"fixed32,3,opt,name=keyword_similarity,json=keywordSimilarity,proto3" json:"keyword_similarity,omitempty"`
	DistanceKm         float64                `protobuf:"fixed64,4,opt,name=distance_km,json=distanceKm,proto3" json:"distance_km,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MatchMetadata) Reset() {
	*x = MatchMetadata{}
	mi := &file_proto_search_search_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchMetadata) ProtoMessage() {}

func (x *MatchMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_search_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchMetadata.ProtoReflect.Descriptor instead.
func (*MatchMetadata) Descriptor() ([]byte, []int) {
	return file_proto_search_search_service_proto_rawDescGZIP(), []int{5}
}

func (x *MatchMetadata) GetMatchedKeywords() []string {
	if x != nil {
		return x.MatchedKeywords
	}
	return nil
}

func (x *MatchMetadata) GetSemanticSimilarity() float32 {
	if x != nil {
		return x.SemanticSimilarity
	}
	return 0
}

func (x *MatchMetadata) GetKeywordSimilarity() float32 {
	if x != nil {
		return x.KeywordSimilarity
	}
	return 0
}

func (x *MatchMetadata) GetDistanceKm() float64 {
	if x != nil {
		return x.DistanceKm
	}
	return 0
}

// User embedding operations
type UpdateUserEmbeddingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *common.UUID           `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProfileText   string                 `protobuf:"bytes,2,opt,name=profile_text,json=profileText,proto3" json:"profile_text,omitempty"`
	ForceUpdate   bool                   `protobuf:"varint,3,opt,name=force_update,json=forceUpdate,proto3" json:"force_update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserEmbeddingRequest) Reset() {
	*x = UpdateUserEmbeddingRequest{}
	mi := &file_proto_search_search_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserEmbeddingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserEmbeddingRequest) ProtoMessage() {}

func (x *UpdateUserEmbeddingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_search_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserEmbeddingRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserEmbeddingRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_search_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateUserEmbeddingRequest) GetUserId() *common.UUID {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *UpdateUserEmbeddingRequest) GetProfileText() string {
	if x != nil {
		return x.ProfileText
	}
	return ""
}

func (x *UpdateUserEmbeddingRequest) GetForceUpdate() bool {
	if x != nil {
		return x.ForceUpdate
	}
	return false
}

type UpdateUserEmbeddingResponse struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	Success         bool                    `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	EmbeddingModel  string                  `protobuf:"bytes,2,opt,name=embedding_model,json=embeddingModel,proto3" json:"embedding_model,omitempty"`
	VectorDimension int32                   `protobuf:"varint,3,opt,name=vector_dimension,json=vectorDimension,proto3" json:"vector_dimension,omitempty"`
	UpdatedAt       *timestamppb.Timestamp  `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Result          *common.SuccessResponse `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateUserEmbeddingResponse) Reset() {
	*x = UpdateUserEmbeddingResponse{}
	mi := &file_proto_search_search_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserEmbeddingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserEmbeddingResponse) ProtoMessage() {}

func (x *UpdateUserEmbeddingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_search_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserEmbeddingResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserEmbeddingResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_search_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateUserEmbeddingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateUserEmbeddingResponse) GetEmbeddingModel() string {
	if x != nil {
		return x.EmbeddingModel
	}
	return ""
}

func (x *UpdateUserEmbeddingResponse) GetVectorDimension() int32 {
	if x != nil {
		return x.VectorDimension
	}
	return 0
}

func (x *UpdateUserEmbeddingResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *UpdateUserEmbeddingResponse) GetResult() *common.SuccessResponse {
	if x != nil {
		return x.Result
	}
	return nil
}

type DeleteUserEmbeddingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *common.UUID           `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserEmbeddingRequest) Reset() {
	*x = DeleteUserEmbeddingRequest{}
	mi := &file_proto_search_search_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserEmbeddingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserEmbeddingRequest) ProtoMessage() {}

func (x *DeleteUserEmbeddingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_search_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserEmbeddingRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserEmbeddingRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_search_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteUserEmbeddingRequest) GetUserId() *common.UUID {
	if x != nil {
		return x.UserId
	}
	return nil
}

type DeleteUserEmbeddingResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Success       bool                    `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Result        *common.SuccessResponse `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserEmbeddingResponse) Reset() {
	*x = DeleteUserEmbeddingResponse{}
	mi := &file_proto_search_search_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserEmbeddingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserEmbeddingResponse) ProtoMessage() {}

func (x *DeleteUserEmbeddingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_search_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserEmbeddingResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserEmbeddingResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_search_service_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteUserEmbeddingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteUserEmbeddingResponse) GetResult() *common.SuccessResponse {
	if x != nil {
		return x.Result
	}
	return nil
}

type HasUserEmbeddingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *common.UUID           `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasUserEmbeddingRequest) Reset() {
	*x = HasUserEmbeddingRequest{}
	mi := &file_proto_search_search_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasUserEmbeddingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasUserEmbeddingRequest) ProtoMessage() {}

func (x *HasUserEmbeddingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_search_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasUserEmbeddingRequest.ProtoReflect.Descriptor instead.
func (*HasUserEmbeddingRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_search_service_proto_rawDescGZIP(), []int{10}
}

func (x *HasUserEmbeddingRequest) GetUserId() *common.UUID {
	if x != nil {
		return x.UserId
	}
	return nil
}

type HasUserEmbeddingResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HasEmbedding   bool                   `protobuf:"varint,1,opt,name=has_embedding,json=hasEmbedding,proto3" json:"has_embedding,omitempty"`
	LastUpdated    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	EmbeddingModel string                 `protobuf:"bytes,3,opt,name=embedding_model,json=embeddingModel,proto3" json:"embedding_model,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HasUserEmbeddingResponse) Reset() {
	*x = HasUserEmbeddingResponse{}
	mi := &file_proto_search_search_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasUserEmbeddingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasUserEmbeddingResponse) ProtoMessage() {}

func (x *HasUserEmbeddingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_search_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasUserEmbeddingResponse.ProtoReflect.Descriptor instead.
func (*HasUserEmbeddingResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_search_service_proto_rawDescGZIP(), []int{11}
}

func (x *HasUserEmbeddingResponse) GetHasEmbedding() bool {
	if x != nil {
		return x.HasEmbedding
	}
	return false
}

func (x *HasUserEmbeddingResponse) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

func (x *HasUserEmbeddingResponse) GetEmbeddingModel() string {
	if x != nil {
		return x.EmbeddingModel
	}
	return ""
}

// Batch operations
type BatchUpdateEmbeddingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updates       []*UserEmbeddingUpdate `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty"`
	ForceUpdate   bool                   `protobuf:"varint,2,opt,name=force_update,json=forceUpdate,proto3" json:"force_update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUpdateEmbeddingsRequest) Reset() {
	*x = BatchUpdateEmbeddingsRequest{}
	mi := &file_proto_search_search_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUpdateEmbeddingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUpdateEmbeddingsRequest) ProtoMessage() {}

func (x *BatchUpdateEmbeddingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_search_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUpdateEmbeddingsRequest.ProtoReflect.Descriptor instead.
func (*BatchUpdateEmbeddingsRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_search_service_proto_rawDescGZIP(), []int{12}
}

func (x *BatchUpdateEmbeddingsRequest) GetUpdates() []*UserEmbeddingUpdate {
	if x != nil {
		return x.Updates
	}
	return nil
}

func (x *BatchUpdateEmbeddingsRequest) GetForceUpdate() bool {
	if x != nil {
		return x.ForceUpdate
	}
	return false
}

type UserEmbeddingUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *common.UUID           `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProfileText   string                 `protobuf:"bytes,2,opt,name=profile_text,json=profileText,proto3" json:"profile_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserEmbeddingUpdate) Reset() {
	*x = UserEmbeddingUpdate{}
	mi := &file_proto_search_search_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserEmbeddingUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEmbeddingUpdate) ProtoMessage() {}

func (x *UserEmbeddingUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_search_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEmbeddingUpdate.ProtoReflect.Descriptor instead.
func (*UserEmbeddingUpdate) Descriptor() ([]byte, []int) {
	return file_proto_search_search_service_proto_rawDescGZIP(), []int{13}
}

func (x *UserEmbeddingUpdate) GetUserId() *common.UUID {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *UserEmbeddingUpdate) GetProfileText() string {
	if x != nil {
		return x.ProfileText
	}
	return ""
}

type BatchUpdateEmbeddingsResponse struct {
	state             protoimpl.MessageState  `protogen:"open.v1"`
	SuccessfulUpdates int32                   `protobuf:"varint,1,opt,name=successful_updates,json=successfulUpdates,proto3" json:"successful_updates,omitempty"`
	FailedUpdates     int32                   `protobuf:"varint,2,opt,name=failed_updates,json=failedUpdates,proto3" json:"failed_updates,omitempty"`
	Errors            []*BatchUpdateError     `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	Result            *common.SuccessResponse `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BatchUpdateEmbeddingsResponse) Reset() {
	*x = BatchUpdateEmbeddingsResponse{}
	mi := &file_proto_search_search_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUpdateEmbeddingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUpdateEmbeddingsResponse) ProtoMessage() {}

func (x *BatchUpdateEmbeddingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_search_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUpdateEmbeddingsResponse.ProtoReflect.Descriptor instead.
func (*BatchUpdateEmbeddingsResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_search_service_proto_rawDescGZIP(), []int{14}
}

func (x *BatchUpdateEmbeddingsResponse) GetSuccessfulUpdates() int32 {
	if x != nil {
		return x.SuccessfulUpdates
	}
	return 0
}

func (x *BatchUpdateEmbeddingsResponse) GetFailedUpdates() int32 {
	if x != nil {
		return x.FailedUpdates
	}
	return 0
}

func (x *BatchUpdateEmbeddingsResponse) GetErrors() []*BatchUpdateError {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *BatchUpdateEmbeddingsResponse) GetResult() *common.SuccessResponse {
	if x != nil {
		return x.Result
	}
	return nil
}

type BatchUpdateError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *common.UUID           `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUpdateError) Reset() {
	*x = BatchUpdateError{}
	mi := &file_proto_search_search_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUpdateError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUpdateError) ProtoMessage() {}

func (x *BatchUpdateError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_search_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUpdateError.ProtoReflect.Descriptor instead.
func (*BatchUpdateError) Descriptor() ([]byte, []int) {
	return file_proto_search_search_service_proto_rawDescGZIP(), []int{15}
}

func (x *BatchUpdateError) GetUserId() *common.UUID {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *BatchUpdateError) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *BatchUpdateError) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

// Reindex operations
type ReindexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []*common.UUID         `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	Options       *ReindexOptions        `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReindexRequest) Reset() {
	*x = ReindexRequest{}
	mi := &file_proto_search_search_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReindexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReindexRequest) ProtoMessage() {}

func (x *ReindexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_search_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReindexRequest.ProtoReflect.Descriptor instead.
func (*ReindexRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_search_service_proto_rawDescGZIP(), []int{16}
}

func (x *ReindexRequest) GetUserIds() []*common.UUID {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *ReindexRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *ReindexRequest) GetOptions() *ReindexOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type ReindexOptions struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UpdateAllEmbeddings bool                   `protobuf:"varint,1,opt,name=update_all_embeddings,json=updateAllEmbeddings,proto3" json:"update_all_embeddings,omitempty"`
	CleanupExpired      bool                   `protobuf:"varint,2,opt,name=cleanup_expired,json=cleanupExpired,proto3" json:"cleanup_expired,omitempty"`
	RebuildIndex        bool                   `protobuf:"varint,3,opt,name=rebuild_index,json=rebuildIndex,proto3" json:"rebuild_index,omitempty"`
	BatchSize           int32                  `protobuf:"varint,4,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ReindexOptions) Reset() {
	*x = ReindexOptions{}
	mi := &file_proto_search_search_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReindexOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReindexOptions) ProtoMessage() {}

func (x *ReindexOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_search_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReindexOptions.ProtoReflect.Descriptor instead.
func (*ReindexOptions) Descriptor() ([]byte, []int) {
	return file_proto_search_search_service_proto_rawDescGZIP(), []int{17}
}

func (x *ReindexOptions) GetUpdateAllEmbeddings() bool {
	if x != nil {
		return x.UpdateAllEmbeddings
	}
	return false
}

func (x *ReindexOptions) GetCleanupExpired() bool {
	if x != nil {
		return x.CleanupExpired
	}
	return false
}

func (x *ReindexOptions) GetRebuildIndex() bool {
	if x != nil {
		return x.RebuildIndex
	}
	return false
}

func (x *ReindexOptions) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

type ReindexResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	JobId               string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status              ReindexStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=search.ReindexStatus" json:"status,omitempty"`
	UsersQueued         int32                  `protobuf:"varint,3,opt,name=users_queued,json=usersQueued,proto3" json:"users_queued,omitempty"`
	EstimatedCompletion *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=estimated_completion,json=estimatedCompletion,proto3" json:"estimated_completion,omitempty"`
	Metadata            *ReindexMetadata       `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ReindexResponse) Reset() {
	*x = ReindexResponse{}
	mi := &file_proto_search_search_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReindexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReindexResponse) ProtoMessage() {}

func (x *ReindexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_search_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReindexResponse.ProtoReflect.Descriptor instead.
func (*ReindexResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_search_service_proto_rawDescGZIP(), []int{18}
}

func (x *ReindexResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ReindexResponse) GetStatus() ReindexStatus {
	if x != nil {
		return x.Status
	}
	return ReindexStatus_PENDING
}

func (x *ReindexResponse) GetUsersQueued() int32 {
	if x != nil {
		return x.UsersQueued
	}
	return 0
}

func (x *ReindexResponse) GetEstimatedCompletion() *timestamppb.Timestamp {
	if x != nil {
		return x.EstimatedCompletion
	}
	return nil
}

func (x *ReindexResponse) GetMetadata() *ReindexMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ReindexMetadata struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BatchSize      int32                  `protobuf:"varint,1,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	EmbeddingModel string                 `protobuf:"bytes,2,opt,name=embedding_model,json=embeddingModel,proto3" json:"embedding_model,omitempty"`
	CleanupEnabled bool                   `protobuf:"varint,3,opt,name=cleanup_enabled,json=cleanupEnabled,proto3" json:"cleanup_enabled,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReindexMetadata) Reset() {
	*x = ReindexMetadata{}
	mi := &file_proto_search_search_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReindexMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReindexMetadata) ProtoMessage() {}

func (x *ReindexMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_search_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReindexMetadata.ProtoReflect.Descriptor instead.
func (*ReindexMetadata) Descriptor() ([]byte, []int) {
	return file_proto_search_search_service_proto_rawDescGZIP(), []int{19}
}

func (x *ReindexMetadata) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *ReindexMetadata) GetEmbeddingModel() string {
	if x != nil {
		return x.EmbeddingModel
	}
	return ""
}

func (x *ReindexMetadata) GetCleanupEnabled() bool {
	if x != nil {
		return x.CleanupEnabled
	}
	return false
}

type ReindexStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReindexStatusRequest) Reset() {
	*x = ReindexStatusRequest{}
	mi := &file_proto_search_search_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReindexStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReindexStatusRequest) ProtoMessage() {}

func (x *ReindexStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_search_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReindexStatusRequest.ProtoReflect.Descriptor instead.
func (*ReindexStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_search_service_proto_rawDescGZIP(), []int{20}
}

func (x *ReindexStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type ReindexStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status         ReindexStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=search.ReindexStatus" json:"status,omitempty"`
	UsersTotal     int32                  `protobuf:"varint,3,opt,name=users_total,json=usersTotal,proto3" json:"users_total,omitempty"`
	UsersProcessed int32                  `protobuf:"varint,4,opt,name=users_processed,json=usersProcessed,proto3" json:"users_processed,omitempty"`
	UsersFailed    int32                  `protobuf:"varint,5,opt,name=users_failed,json=usersFailed,proto3" json:"users_failed,omitempty"`
	StartedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Progress       *ReindexProgress       `protobuf:"bytes,9,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReindexStatusResponse) Reset() {
	*x = ReindexStatusResponse{}
	mi := &file_proto_search_search_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReindexStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReindexStatusResponse) ProtoMessage() {}

func (x *ReindexStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_search_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReindexStatusResponse.ProtoReflect.Descriptor instead.
func (*ReindexStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_search_service_proto_rawDescGZIP(), []int{21}
}

func (x *ReindexStatusResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ReindexStatusResponse) GetStatus() ReindexStatus {
	if x != nil {
		return x.Status
	}
	return ReindexStatus_PENDING
}

func (x *ReindexStatusResponse) GetUsersTotal() int32 {
	if x != nil {
		return x.UsersTotal
	}
	return 0
}

func (x *ReindexStatusResponse) GetUsersProcessed() int32 {
	if x != nil {
		return x.UsersProcessed
	}
	return 0
}

func (x *ReindexStatusResponse) GetUsersFailed() int32 {
	if x != nil {
		return x.UsersFailed
	}
	return 0
}

func (x *ReindexStatusResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ReindexStatusResponse) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *ReindexStatusResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ReindexStatusResponse) GetProgress() *ReindexProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

type StreamReindexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamReindexRequest) Reset() {
	*x = StreamReindexRequest{}
	mi := &file_proto_search_search_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamReindexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamReindexRequest) ProtoMessage() {}

func (x *StreamReindexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_search_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamReindexRequest.ProtoReflect.Descriptor instead.
func (*StreamReindexRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_search_service_proto_rawDescGZIP(), []int{22}
}

func (x *StreamReindexRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type ReindexProgress struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	JobId              string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status             ReindexStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=search.ReindexStatus" json:"status,omitempty"`
	UsersProcessed     int32                  `protobuf:"varint,3,opt,name=users_processed,json=usersProcessed,proto3" json:"users_processed,omitempty"`
	UsersTotal         int32                  `protobuf:"varint,4,opt,name=users_total,json=usersTotal,proto3" json:"users_total,omitempty"`
	ProgressPercentage float32                `protobuf:"fixed32,5,opt,name=progress_percentage,json=progressPercentage,proto3" json:"progress_percentage,omitempty"`
	CurrentBatch       int32                  `protobuf:"varint,6,opt,name=current_batch,json=currentBatch,proto3" json:"current_batch,omitempty"`
	TotalBatches       int32                  `protobuf:"varint,7,opt,name=total_batches,json=totalBatches,proto3" json:"total_batches,omitempty"`
	LastUpdate         *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	CurrentOperation   string                 `protobuf:"bytes,9,opt,name=current_operation,json=currentOperation,proto3" json:"current_operation,omitempty"`
	RecentErrors       []string               `protobuf:"bytes,10,rep,name=recent_errors,json=recentErrors,proto3" json:"recent_errors,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ReindexProgress) Reset() {
	*x = ReindexProgress{}
	mi := &file_proto_search_search_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReindexProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReindexProgress) ProtoMessage() {}

func (x *ReindexProgress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_search_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReindexProgress.ProtoReflect.Descriptor instead.
func (*ReindexProgress) Descriptor() ([]byte, []int) {
	return file_proto_search_search_service_proto_rawDescGZIP(), []int{23}
}

func (x *ReindexProgress) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ReindexProgress) GetStatus() ReindexStatus {
	if x != nil {
		return x.Status
	}
	return ReindexStatus_PENDING
}

func (x *ReindexProgress) GetUsersProcessed() int32 {
	if x != nil {
		return x.UsersProcessed
	}
	return 0
}

func (x *ReindexProgress) GetUsersTotal() int32 {
	if x != nil {
		return x.UsersTotal
	}
	return 0
}

func (x *ReindexProgress) GetProgressPercentage() float32 {
	if x != nil {
		return x.ProgressPercentage
	}
	return 0
}

func (x *ReindexProgress) GetCurrentBatch() int32 {
	if x != nil {
		return x.CurrentBatch
	}
	return 0
}

func (x *ReindexProgress) GetTotalBatches() int32 {
	if x != nil {
		return x.TotalBatches
	}
	return 0
}

func (x *ReindexProgress) GetLastUpdate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdate
	}
	return nil
}

func (x *ReindexProgress) GetCurrentOperation() string {
	if x != nil {
		return x.CurrentOperation
	}
	return ""
}

func (x *ReindexProgress) GetRecentErrors() []string {
	if x != nil {
		return x.RecentErrors
	}
	return nil
}

var File_proto_search_search_service_proto protoreflect.FileDescriptor

const file_proto_search_search_service_proto_rawDesc = "" +
	"\n" +
	"!proto/search/search_service.proto\x12\x06search\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18proto/common/types.proto\"\xe4\x02\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12'\n" +
	"\buser_ids\x18\x03 \x03(\v2\f.common.UUIDR\auserIds\x124\n" +
	"\x0fexclude_user_id\x18\x04 \x01(\v2\f.common.UUIDR\rexcludeUserId\x12)\n" +
	"\x05scope\x18\x05 \x01(\x0e2\x13.search.SearchScopeR\x05scope\x12:\n" +
	"\x12requesting_user_id\x18\x06 \x01(\v2\f.common.UUIDR\x10requestingUserId\x129\n" +
	"\x0fcenter_location\x18\a \x01(\v2\x10.search.LocationR\x0ecenterLocation\x12&\n" +
	"\x0fmax_distance_km\x18\b \x01(\x01R\rmaxDistanceKm\"`\n" +
	"\bLocation\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\baccuracy\x18\x03 \x01(\x01R\baccuracy\"\xee\x01\n" +
	"\x0eSearchResponse\x12.\n" +
	"\aresults\x18\x01 \x03(\v2\x14.search.SearchResultR\aresults\x12'\n" +
	"\x0fquery_processed\x18\x02 \x01(\tR\x0equeryProcessed\x12)\n" +
	"\x10total_candidates\x18\x03 \x01(\x05R\x0ftotalCandidates\x12$\n" +
	"\x0esearch_time_ms\x18\x04 \x01(\x05R\fsearchTimeMs\x122\n" +
	"\bmetadata\x18\x05 \x01(\v2\x16.search.SearchMetadataR\bmetadata\"\xc9\x01\n" +
	"\x0eSearchMetadata\x122\n" +
	"\n" +
	"scope_used\x18\x01 \x01(\x0e2\x13.search.SearchScopeR\tscopeUsed\x12/\n" +
	"\x13embedding_generated\x18\x02 \x01(\bR\x12embeddingGenerated\x12'\n" +
	"\x0fembedding_model\x18\x03 \x01(\tR\x0eembeddingModel\x12)\n" +
	"\x10vector_dimension\x18\x04 \x01(\x05R\x0fvectorDimension\"\xae\x01\n" +
	"\fSearchResult\x12%\n" +
	"\auser_id\x18\x01 \x01(\v2\f.common.UUIDR\x06userId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12#\n" +
	"\rmatch_reasons\x18\x03 \x03(\tR\fmatchReasons\x12<\n" +
	"\x0ematch_metadata\x18\x04 \x01(\v2\x15.search.MatchMetadataR\rmatchMetadata\"\xbb\x01\n" +
	"\rMatchMetadata\x12)\n" +
	"\x10matched_keywords\x18\x01 \x03(\tR\x0fmatchedKeywords\x12/\n" +
	"\x13semantic_similarity\x18\x02 \x01(\x02R\x12semanticSimilarity\x12-\n" +
	"\x12keyword_similarity\x18\x03 \x01(\x02R\x11keywordSimilarity\x12\x1f\n" +
	"\vdistance_km\x18\x04 \x01(\x01R\n" +
	"distanceKm\"\x89\x01\n" +
	"\x1aUpdateUserEmbeddingRequest\x12%\n" +
	"\auser_id\x18\x01 \x01(\v2\f.common.UUIDR\x06userId\x12!\n" +
	"\fprofile_text\x18\x02 \x01(\tR\vprofileText\x12!\n" +
	"\fforce_update\x18\x03 \x01(\bR\vforceUpdate\"\xf7\x01\n" +
	"\x1bUpdateUserEmbeddingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0fembedding_model\x18\x02 \x01(\tR\x0eembeddingModel\x12)\n" +
	"\x10vector_dimension\x18\x03 \x01(\x05R\x0fvectorDimension\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12/\n" +
	"\x06result\x18\x05 \x01(\v2\x17.common.SuccessResponseR\x06result\"C\n" +
	"\x1aDeleteUserEmbeddingRequest\x12%\n" +
	"\auser_id\x18\x01 \x01(\v2\f.common.UUIDR\x06userId\"h\n" +
	"\x1bDeleteUserEmbeddingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12/\n" +
	"\x06result\x18\x02 \x01(\v2\x17.common.SuccessResponseR\x06result\"@\n" +
	"\x17HasUserEmbeddingRequest\x12%\n" +
	"\auser_id\x18\x01 \x01(\v2\f.common.UUIDR\x06userId\"\xa7\x01\n" +
	"\x18HasUserEmbeddingResponse\x12#\n" +
	"\rhas_embedding\x18\x01 \x01(\bR\fhasEmbedding\x12=\n" +
	"\flast_updated\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\x12'\n" +
	"\x0fembedding_model\x18\x03 \x01(\tR\x0eembeddingModel\"x\n" +
	"\x1cBatchUpdateEmbeddingsRequest\x125\n" +
	"\aupdates\x18\x01 \x03(\v2\x1b.search.UserEmbeddingUpdateR\aupdates\x12!\n" +
	"\fforce_update\x18\x02 \x01(\bR\vforceUpdate\"_\n" +
	"\x13UserEmbeddingUpdate\x12%\n" +
	"\auser_id\x18\x01 \x01(\v2\f.common.UUIDR\x06userId\x12!\n" +
	"\fprofile_text\x18\x02 \x01(\tR\vprofileText\"\xd8\x01\n" +
	"\x1dBatchUpdateEmbeddingsResponse\x12-\n" +
	"\x12successful_updates\x18\x01 \x01(\x05R\x11successfulUpdates\x12%\n" +
	"\x0efailed_updates\x18\x02 \x01(\x05R\rfailedUpdates\x120\n" +
	"\x06errors\x18\x03 \x03(\v2\x18.search.BatchUpdateErrorR\x06errors\x12/\n" +
	"\x06result\x18\x04 \x01(\v2\x17.common.SuccessResponseR\x06result\"}\n" +
	"\x10BatchUpdateError\x12%\n" +
	"\auser_id\x18\x01 \x01(\v2\f.common.UUIDR\x06userId\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\"\x81\x01\n" +
	"\x0eReindexRequest\x12'\n" +
	"\buser_ids\x18\x01 \x03(\v2\f.common.UUIDR\auserIds\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\x120\n" +
	"\aoptions\x18\x03 \x01(\v2\x16.search.ReindexOptionsR\aoptions\"\xb1\x01\n" +
	"\x0eReindexOptions\x122\n" +
	"\x15update_all_embeddings\x18\x01 \x01(\bR\x13updateAllEmbeddings\x12'\n" +
	"\x0fcleanup_expired\x18\x02 \x01(\bR\x0ecleanupExpired\x12#\n" +
	"\rrebuild_index\x18\x03 \x01(\bR\frebuildIndex\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x04 \x01(\x05R\tbatchSize\"\xfe\x01\n" +
	"\x0fReindexResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.search.ReindexStatusR\x06status\x12!\n" +
	"\fusers_queued\x18\x03 \x01(\x05R\vusersQueued\x12M\n" +
	"\x14estimated_completion\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x13estimatedCompletion\x123\n" +
	"\bmetadata\x18\x05 \x01(\v2\x17.search.ReindexMetadataR\bmetadata\"\x82\x01\n" +
	"\x0fReindexMetadata\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x01 \x01(\x05R\tbatchSize\x12'\n" +
	"\x0fembedding_model\x18\x02 \x01(\tR\x0eembeddingModel\x12'\n" +
	"\x0fcleanup_enabled\x18\x03 \x01(\bR\x0ecleanupEnabled\"-\n" +
	"\x14ReindexStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x9e\x03\n" +
	"\x15ReindexStatusResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.search.ReindexStatusR\x06status\x12\x1f\n" +
	"\vusers_total\x18\x03 \x01(\x05R\n" +
	"usersTotal\x12'\n" +
	"\x0fusers_processed\x18\x04 \x01(\x05R\x0eusersProcessed\x12!\n" +
	"\fusers_failed\x18\x05 \x01(\x05R\vusersFailed\x129\n" +
	"\n" +
	"started_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\x123\n" +
	"\bprogress\x18\t \x01(\v2\x17.search.ReindexProgressR\bprogress\"-\n" +
	"\x14StreamReindexRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\xab\x03\n" +
	"\x0fReindexProgress\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.search.ReindexStatusR\x06status\x12'\n" +
	"\x0fusers_processed\x18\x03 \x01(\x05R\x0eusersProcessed\x12\x1f\n" +
	"\vusers_total\x18\x04 \x01(\x05R\n" +
	"usersTotal\x12/\n" +
	"\x13progress_percentage\x18\x05 \x01(\x02R\x12progressPercentage\x12#\n" +
	"\rcurrent_batch\x18\x06 \x01(\x05R\fcurrentBatch\x12#\n" +
	"\rtotal_batches\x18\a \x01(\x05R\ftotalBatches\x12;\n" +
	"\vlast_update\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUpdate\x12+\n" +
	"\x11current_operation\x18\t \x01(\tR\x10currentOperation\x12#\n" +
	"\rrecent_errors\x18\n" +
	" \x03(\tR\frecentErrors*D\n" +
	"\vSearchScope\x12\r\n" +
	"\tALL_USERS\x10\x00\x12\v\n" +
	"\aFRIENDS\x10\x01\x12\r\n" +
	"\tDISCOVERY\x10\x02\x12\n" +
	"\n" +
	"\x06NEARBY\x10\x03*S\n" +
	"\rReindexStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\v\n" +
	"\aRUNNING\x10\x01\x12\r\n" +
	"\tCOMPLETED\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03\x12\r\n" +
	"\tCANCELLED\x10\x042\xe7\x05\n" +
	"\rSearchService\x127\n" +
	"\x06Search\x12\x15.search.SearchRequest\x1a\x16.search.SearchResponse\x12^\n" +
	"\x13UpdateUserEmbedding\x12\".search.UpdateUserEmbeddingRequest\x1a#.search.UpdateUserEmbeddingResponse\x12^\n" +
	"\x13DeleteUserEmbedding\x12\".search.DeleteUserEmbeddingRequest\x1a#.search.DeleteUserEmbeddingResponse\x12U\n" +
	"\x10HasUserEmbedding\x12\x1f.search.HasUserEmbeddingRequest\x1a .search.HasUserEmbeddingResponse\x12d\n" +
	"\x15BatchUpdateEmbeddings\x12$.search.BatchUpdateEmbeddingsRequest\x1a%.search.BatchUpdateEmbeddingsResponse\x12:\n" +
	"\aReindex\x12\x16.search.ReindexRequest\x1a\x17.search.ReindexResponse\x12O\n" +
	"\x10GetReindexStatus\x12\x1c.search.ReindexStatusRequest\x1a\x1d.search.ReindexStatusResponse\x12P\n" +
	"\x15StreamReindexProgress\x12\x1c.search.StreamReindexRequest\x1a\x17.search.ReindexProgress0\x01\x12A\n" +
	"\x06Health\x12\x1a.common.HealthCheckRequest\x1a\x1b.common.HealthCheckResponseB*Z(github.com/link-app/backend/proto/searchb\x06proto3"

var (
	file_proto_search_search_service_proto_rawDescOnce sync.Once
	file_proto_search_search_service_proto_rawDescData []byte
)

func file_proto_search_search_service_proto_rawDescGZIP() []byte {
	file_proto_search_search_service_proto_rawDescOnce.Do(func() {
		file_proto_search_search_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_search_search_service_proto_rawDesc), len(file_proto_search_search_service_proto_rawDesc)))
	})
	return file_proto_search_search_service_proto_rawDescData
}

var file_proto_search_search_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_search_search_service_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_proto_search_search_service_proto_goTypes = []any{
	(SearchScope)(0),                      // 0: search.SearchScope
	(ReindexStatus)(0),                    // 1: search.ReindexStatus
	(*SearchRequest)(nil),                 // 2: search.SearchRequest
	(*Location)(nil),                      // 3: search.Location
	(*SearchResponse)(nil),                // 4: search.SearchResponse
	(*SearchMetadata)(nil),                // 5: search.SearchMetadata
	(*SearchResult)(nil),                  // 6: search.SearchResult
	(*MatchMetadata)(nil),                 // 7: search.MatchMetadata
	(*UpdateUserEmbeddingRequest)(nil),    // 8: search.UpdateUserEmbeddingRequest
	(*UpdateUserEmbeddingResponse)(nil),   // 9: search.UpdateUserEmbeddingResponse
	(*DeleteUserEmbeddingRequest)(nil),    // 10: search.DeleteUserEmbeddingRequest
	(*DeleteUserEmbeddingResponse)(nil),   // 11: search.DeleteUserEmbeddingResponse
	(*HasUserEmbeddingRequest)(nil),       // 12: search.HasUserEmbeddingRequest
	(*HasUserEmbeddingResponse)(nil),      // 13: search.HasUserEmbeddingResponse
	(*BatchUpdateEmbeddingsRequest)(nil),  // 14: search.BatchUpdateEmbeddingsRequest
	(*UserEmbeddingUpdate)(nil),           // 15: search.UserEmbeddingUpdate
	(*BatchUpdateEmbeddingsResponse)(nil), // 16: search.BatchUpdateEmbeddingsResponse
	(*BatchUpdateError)(nil),              // 17: search.BatchUpdateError
	(*ReindexRequest)(nil),                // 18: search.ReindexRequest
	(*ReindexOptions)(nil),                // 19: search.ReindexOptions
	(*ReindexResponse)(nil),               // 20: search.ReindexResponse
	(*ReindexMetadata)(nil),               // 21: search.ReindexMetadata
	(*ReindexStatusRequest)(nil),          // 22: search.ReindexStatusRequest
	(*ReindexStatusResponse)(nil),         // 23: search.ReindexStatusResponse
	(*StreamReindexRequest)(nil),          // 24: search.StreamReindexRequest
	(*ReindexProgress)(nil),               // 25: search.ReindexProgress
	(*common.UUID)(nil),                   // 26: common.UUID
	(*timestamppb.Timestamp)(nil),         // 27: google.protobuf.Timestamp
	(*common.SuccessResponse)(nil),        // 28: common.SuccessResponse
	(*common.HealthCheckRequest)(nil),     // 29: common.HealthCheckRequest
	(*common.HealthCheckResponse)(nil),    // 30: common.HealthCheckResponse
}
var file_proto_search_search_service_proto_depIdxs = []int32{
	26, // 0: search.SearchRequest.user_ids:type_name -> common.UUID
	26, // 1: search.SearchRequest.exclude_user_id:type_name -> common.UUID
	0,  // 2: search.SearchRequest.scope:type_name -> search.SearchScope
	26, // 3: search.SearchRequest.requesting_user_id:type_name -> common.UUID
	3,  // 4: search.SearchRequest.center_location:type_name -> search.Location
	6,  // 5: search.SearchResponse.results:type_name -> search.SearchResult
	5,  // 6: search.SearchResponse.metadata:type_name -> search.SearchMetadata
	0,  // 7: search.SearchMetadata.scope_used:type_name -> search.SearchScope
	26, // 8: search.SearchResult.user_id:type_name -> common.UUID
	7,  // 9: search.SearchResult.match_metadata:type_name -> search.MatchMetadata
	26, // 10: search.UpdateUserEmbeddingRequest.user_id:type_name -> common.UUID
	27, // 11: search.UpdateUserEmbeddingResponse.updated_at:type_name -> google.protobuf.Timestamp
	28, // 12: search.UpdateUserEmbeddingResponse.result:type_name -> common.SuccessResponse
	26, // 13: search.DeleteUserEmbeddingRequest.user_id:type_name -> common.UUID
	28, // 14: search.DeleteUserEmbeddingResponse.result:type_name -> common.SuccessResponse
	26, // 15: search.HasUserEmbeddingRequest.user_id:type_name -> common.UUID
	27, // 16: search.HasUserEmbeddingResponse.last_updated:type_name -> google.protobuf.Timestamp
	15, // 17: search.BatchUpdateEmbeddingsRequest.updates:type_name -> search.UserEmbeddingUpdate
	26, // 18: search.UserEmbeddingUpdate.user_id:type_name -> common.UUID
	17, // 19: search.BatchUpdateEmbeddingsResponse.errors:type_name -> search.BatchUpdateError
	28, // 20: search.BatchUpdateEmbeddingsResponse.result:type_name -> common.SuccessResponse
	26, // 21: search.BatchUpdateError.user_id:type_name -> common.UUID
	26, // 22: search.ReindexRequest.user_ids:type_name -> common.UUID
	19, // 23: search.ReindexRequest.options:type_name -> search.ReindexOptions
	1,  // 24: search.ReindexResponse.status:type_name -> search.ReindexStatus
	27, // 25: search.ReindexResponse.estimated_completion:type_name -> google.protobuf.Timestamp
	21, // 26: search.ReindexResponse.metadata:type_name -> search.ReindexMetadata
	1,  // 27: search.ReindexStatusResponse.status:type_name -> search.ReindexStatus
	27, // 28: search.ReindexStatusResponse.started_at:type_name -> google.protobuf.Timestamp
	27, // 29: search.ReindexStatusResponse.completed_at:type_name -> google.protobuf.Timestamp
	25, // 30: search.ReindexStatusResponse.progress:type_name -> search.ReindexProgress
	1,  // 31: search.ReindexProgress.status:type_name -> search.ReindexStatus
	27, // 32: search.ReindexProgress.last_update:type_name -> google.protobuf.Timestamp
	2,  // 33: search.SearchService.Search:input_type -> search.SearchRequest
	8,  // 34: search.SearchService.UpdateUserEmbedding:input_type -> search.UpdateUserEmbeddingRequest
	10, // 35: search.SearchService.DeleteUserEmbedding:input_type -> search.DeleteUserEmbeddingRequest
	12, // 36: search.SearchService.HasUserEmbedding:input_type -> search.HasUserEmbeddingRequest
	14, // 37: search.SearchService.BatchUpdateEmbeddings:input_type -> search.BatchUpdateEmbeddingsRequest
	18, // 38: search.SearchService.Reindex:input_type -> search.ReindexRequest
	22, // 39: search.SearchService.GetReindexStatus:input_type -> search.ReindexStatusRequest
	24, // 40: search.SearchService.StreamReindexProgress:input_type -> search.StreamReindexRequest
	29, // 41: search.SearchService.Health:input_type -> common.HealthCheckRequest
	4,  // 42: search.SearchService.Search:output_type -> search.SearchResponse
	9,  // 43: search.SearchService.UpdateUserEmbedding:output_type -> search.UpdateUserEmbeddingResponse
	11, // 44: search.SearchService.DeleteUserEmbedding:output_type -> search.DeleteUserEmbeddingResponse
	13, // 45: search.SearchService.HasUserEmbedding:output_type -> search.HasUserEmbeddingResponse
	16, // 46: search.SearchService.BatchUpdateEmbeddings:output_type -> search.BatchUpdateEmbeddingsResponse
	20, // 47: search.SearchService.Reindex:output_type -> search.ReindexResponse
	23, // 48: search.SearchService.GetReindexStatus:output_type -> search.ReindexStatusResponse
	25, // 49: search.SearchService.StreamReindexProgress:output_type -> search.ReindexProgress
	30, // 50: search.SearchService.Health:output_type -> common.HealthCheckResponse
	42, // [42:51] is the sub-list for method output_type
	33, // [33:42] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_proto_search_search_service_proto_init() }
func file_proto_search_search_service_proto_init() {
	if File_proto_search_search_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_search_search_service_proto_rawDesc), len(file_proto_search_search_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_search_search_service_proto_goTypes,
		DependencyIndexes: file_proto_search_search_service_proto_depIdxs,
		EnumInfos:         file_proto_search_search_service_proto_enumTypes,
		MessageInfos:      file_proto_search_search_service_proto_msgTypes,
	}.Build()
	File_proto_search_search_service_proto = out.File
	file_proto_search_search_service_proto_goTypes = nil
	file_proto_search_search_service_proto_depIdxs = nil
}
