# Docker Compose overrides for Staging environment
version: '3.8'

services:
  ai-svc:
    image: ${DOCKER_REGISTRY}ai-svc:${VERSION}
    build: null  # Don't build in staging, use pre-built image
    environment:
      - ENVIRONMENT=staging
      - LOG_LEVEL=info
      - DB_SSL_MODE=require
      - RATE_LIMIT_REQUESTS_PER_MINUTE=120  # Higher limits for staging
      - RATE_LIMIT_AI_REQUESTS_PER_MINUTE=20
      - CORS_ALLOWED_ORIGINS=https://staging.linkchatsummary.com,https://app-staging.linkchatsummary.com
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ai-svc-staging.rule=Host(`api-staging.linkchatsummary.com`)"
      - "traefik.http.routers.ai-svc-staging.tls=true"
      - "traefik.http.routers.ai-svc-staging.tls.certresolver=letsencrypt"

  postgres:
    environment:
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256 --auth-local=scram-sha-256
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  redis:
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --save 900 1
      --save 300 10
      --save 60 10000
      --appendonly yes
      --appendfsync everysec
      --tcp-keepalive 60
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  # Remove development-only services
  redis-commander:
    profiles:
      - disabled

  # Enable monitoring for staging
  prometheus:
    profiles:
      - staging
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  grafana:
    profiles:
      - staging
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_SERVER_ROOT_URL=https://monitoring-staging.linkchatsummary.com
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=false
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
