# Search Service Environment Configuration
# Generated by Terraform for ${environment} environment

# Repository Configuration
SEARCH_REPOSITORY_TYPE=${repository_type}

# Qdrant Configuration
QDRANT_HOST=${qdrant_host}
QDRANT_PORT=${qdrant_port}
QDRANT_USE_TLS=${qdrant_use_tls}
QDRANT_CLOUD=${qdrant_cloud}
QDRANT_COLLECTION=${qdrant_collection}
QDRANT_TIMEOUT=${qdrant_timeout}

# Database Configuration (for reindex job tracking)
DB_HOST=${db_host}
DB_PORT=${db_port}
DB_NAME=${db_name}
DB_USER=${db_user}
DB_PASSWORD=$${DB_PASSWORD}
DB_SSLMODE=${db_sslmode}

# OpenAI Configuration
OPENAI_API_KEY=$${OPENAI_API_KEY}
EMBEDDING_PROVIDER=${embedding_provider}
EMBEDDING_MODEL=${embedding_model}

# Service Configuration
PORT=${service_port}
ENVIRONMENT=${environment}
GIN_MODE=${gin_mode}
LOG_LEVEL=${log_level}

# Service Discovery
DISCOVERY_SVC_URL=${discovery_svc_url}
USER_SVC_URL=${user_svc_url}
SERVICE_AUTH_TOKEN=$${SERVICE_AUTH_TOKEN}

# Indexing Pipeline Configuration
INDEXING_CRON_INTERVAL_MINUTES=${indexing_cron_interval_minutes}
INDEXING_WORKER_POOL_SIZE=${indexing_worker_pool_size}
INDEXING_RATE_LIMIT_PER_SECOND=${indexing_rate_limit_per_second}
INDEXING_BATCH_SIZE=${indexing_batch_size}
INDEXING_EMBEDDING_TTL_HOURS=${indexing_embedding_ttl_hours}

# Privacy & Security Safeguards
DB_ENCRYPTION_ENABLED=${db_encryption_enabled}
SEARCH_RATE_LIMIT_QPM=${search_rate_limit_qpm}
ENFORCE_PRIVACY_CHECKS=${enforce_privacy_checks}
ENFORCE_AVAILABILITY_CHECKS=${enforce_availability_checks}

# Caching Configuration
CACHE_TTL=${cache_ttl}

# IMPORTANT: Set these secrets via environment variables:
# export OPENAI_API_KEY="sk-your-openai-api-key"
# export SERVICE_AUTH_TOKEN="your-secure-service-token"
# export DB_PASSWORD="your-secure-db-password"