apiVersion: v1
kind: Service
metadata:
  name: pgbouncer-service
  namespace: link-services
  labels:
    app: pgbouncer
    component: connection-pool
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9127"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
    protocol: TCP
  - name: metrics
    port: 9127
    targetPort: 9127
    protocol: TCP
  selector:
    app: pgbouncer
  sessionAffinity: None

---
apiVersion: v1
kind: Service
metadata:
  name: pgbouncer-headless
  namespace: link-services
  labels:
    app: pgbouncer
    component: connection-pool
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: pgbouncer

---
# ServiceMonitor for Prometheus scraping
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pgbouncer-metrics
  namespace: link-services
  labels:
    app: pgbouncer
    component: connection-pool
spec:
  selector:
    matchLabels:
      app: pgbouncer
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - link-services
