global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'link-monitor'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "rules/database_alerts.yml"  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API Gateway
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # Backend Services
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-svc:8080']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'chat-service'
    static_configs:
      - targets: ['chat-svc:8080']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'ai-service'
    static_configs:
      - targets: ['ai-svc:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 15s

  - job_name: 'discovery-service'
    static_configs:
      - targets: ['discovery-svc:8080']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Infrastructure Services
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # System Metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s

  # Uptime Monitoring
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://api-gateway:8080/health
        - http://user-svc:8080/health
        - http://chat-svc:8080/health
        - http://discovery-svc:8080/health
        - http://frontend:3000
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Frontend Monitoring (if metrics endpoint exists)
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
