// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/user/user_service.proto

package user

import (
	common "github.com/link-app/backend/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Friendship status enum
type FriendshipStatus int32

const (
	FriendshipStatus_UNKNOWN  FriendshipStatus = 0
	FriendshipStatus_PENDING  FriendshipStatus = 1
	FriendshipStatus_ACCEPTED FriendshipStatus = 2
	FriendshipStatus_BLOCKED  FriendshipStatus = 3
)

// Enum value maps for FriendshipStatus.
var (
	FriendshipStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "PENDING",
		2: "ACCEPTED",
		3: "BLOCKED",
	}
	FriendshipStatus_value = map[string]int32{
		"UNKNOWN":  0,
		"PENDING":  1,
		"ACCEPTED": 2,
		"BLOCKED":  3,
	}
)

func (x FriendshipStatus) Enum() *FriendshipStatus {
	p := new(FriendshipStatus)
	*p = x
	return p
}

func (x FriendshipStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FriendshipStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_user_user_service_proto_enumTypes[0].Descriptor()
}

func (FriendshipStatus) Type() protoreflect.EnumType {
	return &file_proto_user_user_service_proto_enumTypes[0]
}

func (x FriendshipStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FriendshipStatus.Descriptor instead.
func (FriendshipStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_user_user_service_proto_rawDescGZIP(), []int{0}
}

// User profile message
type UserProfile struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              *common.UUID           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username        string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email           string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	FirstName       string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName        string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Bio             string                 `protobuf:"bytes,6,opt,name=bio,proto3" json:"bio,omitempty"`
	Interests       []string               `protobuf:"bytes,7,rep,name=interests,proto3" json:"interests,omitempty"`
	Profession      string                 `protobuf:"bytes,8,opt,name=profession,proto3" json:"profession,omitempty"`
	Skills          []string               `protobuf:"bytes,9,rep,name=skills,proto3" json:"skills,omitempty"`
	Location        string                 `protobuf:"bytes,10,opt,name=location,proto3" json:"location,omitempty"`
	AvatarUrl       string                 `protobuf:"bytes,11,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	DateOfBirth     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IsVerified      bool                   `protobuf:"varint,15,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	IsActive        bool                   `protobuf:"varint,16,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	PrivacySettings *PrivacySettings       `protobuf:"bytes,17,opt,name=privacy_settings,json=privacySettings,proto3" json:"privacy_settings,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_proto_user_user_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_proto_user_user_service_proto_rawDescGZIP(), []int{0}
}

func (x *UserProfile) GetId() *common.UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *UserProfile) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserProfile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserProfile) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserProfile) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UserProfile) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UserProfile) GetInterests() []string {
	if x != nil {
		return x.Interests
	}
	return nil
}

func (x *UserProfile) GetProfession() string {
	if x != nil {
		return x.Profession
	}
	return ""
}

func (x *UserProfile) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *UserProfile) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UserProfile) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UserProfile) GetDateOfBirth() *timestamppb.Timestamp {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

func (x *UserProfile) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserProfile) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *UserProfile) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

func (x *UserProfile) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *UserProfile) GetPrivacySettings() *PrivacySettings {
	if x != nil {
		return x.PrivacySettings
	}
	return nil
}

// Privacy settings
type PrivacySettings struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ProfileVisible      bool                   `protobuf:"varint,1,opt,name=profile_visible,json=profileVisible,proto3" json:"profile_visible,omitempty"`
	ShowLocation        bool                   `protobuf:"varint,2,opt,name=show_location,json=showLocation,proto3" json:"show_location,omitempty"`
	ShowAge             bool                   `protobuf:"varint,3,opt,name=show_age,json=showAge,proto3" json:"show_age,omitempty"`
	AllowFriendRequests bool                   `protobuf:"varint,4,opt,name=allow_friend_requests,json=allowFriendRequests,proto3" json:"allow_friend_requests,omitempty"`
	ShowOnlineStatus    bool                   `protobuf:"varint,5,opt,name=show_online_status,json=showOnlineStatus,proto3" json:"show_online_status,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PrivacySettings) Reset() {
	*x = PrivacySettings{}
	mi := &file_proto_user_user_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivacySettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivacySettings) ProtoMessage() {}

func (x *PrivacySettings) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivacySettings.ProtoReflect.Descriptor instead.
func (*PrivacySettings) Descriptor() ([]byte, []int) {
	return file_proto_user_user_service_proto_rawDescGZIP(), []int{1}
}

func (x *PrivacySettings) GetProfileVisible() bool {
	if x != nil {
		return x.ProfileVisible
	}
	return false
}

func (x *PrivacySettings) GetShowLocation() bool {
	if x != nil {
		return x.ShowLocation
	}
	return false
}

func (x *PrivacySettings) GetShowAge() bool {
	if x != nil {
		return x.ShowAge
	}
	return false
}

func (x *PrivacySettings) GetAllowFriendRequests() bool {
	if x != nil {
		return x.AllowFriendRequests
	}
	return false
}

func (x *PrivacySettings) GetShowOnlineStatus() bool {
	if x != nil {
		return x.ShowOnlineStatus
	}
	return false
}

// Friend relationship
type Friend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *common.UUID           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Bio           string                 `protobuf:"bytes,5,opt,name=bio,proto3" json:"bio,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,6,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Status        FriendshipStatus       `protobuf:"varint,7,opt,name=status,proto3,enum=user.FriendshipStatus" json:"status,omitempty"`
	FriendsSince  *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=friends_since,json=friendsSince,proto3" json:"friends_since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Friend) Reset() {
	*x = Friend{}
	mi := &file_proto_user_user_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Friend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Friend) ProtoMessage() {}

func (x *Friend) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Friend.ProtoReflect.Descriptor instead.
func (*Friend) Descriptor() ([]byte, []int) {
	return file_proto_user_user_service_proto_rawDescGZIP(), []int{2}
}

func (x *Friend) GetId() *common.UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Friend) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Friend) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Friend) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Friend) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *Friend) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Friend) GetStatus() FriendshipStatus {
	if x != nil {
		return x.Status
	}
	return FriendshipStatus_UNKNOWN
}

func (x *Friend) GetFriendsSince() *timestamppb.Timestamp {
	if x != nil {
		return x.FriendsSince
	}
	return nil
}

// Request messages
type GetUserProfileRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UserId               *common.UUID           `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IncludePrivateFields bool                   `protobuf:"varint,2,opt,name=include_private_fields,json=includePrivateFields,proto3" json:"include_private_fields,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetUserProfileRequest) Reset() {
	*x = GetUserProfileRequest{}
	mi := &file_proto_user_user_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileRequest) ProtoMessage() {}

func (x *GetUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileRequest.ProtoReflect.Descriptor instead.
func (*GetUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_user_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserProfileRequest) GetUserId() *common.UUID {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *GetUserProfileRequest) GetIncludePrivateFields() bool {
	if x != nil {
		return x.IncludePrivateFields
	}
	return false
}

type GetUserProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserProfile           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileResponse) Reset() {
	*x = GetUserProfileResponse{}
	mi := &file_proto_user_user_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileResponse) ProtoMessage() {}

func (x *GetUserProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileResponse.ProtoReflect.Descriptor instead.
func (*GetUserProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_user_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserProfileResponse) GetUser() *UserProfile {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserFriendsRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	UserId        *common.UUID              `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pagination    *common.PaginationRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	StatusFilter  FriendshipStatus          `protobuf:"varint,3,opt,name=status_filter,json=statusFilter,proto3,enum=user.FriendshipStatus" json:"status_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserFriendsRequest) Reset() {
	*x = GetUserFriendsRequest{}
	mi := &file_proto_user_user_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserFriendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserFriendsRequest) ProtoMessage() {}

func (x *GetUserFriendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserFriendsRequest.ProtoReflect.Descriptor instead.
func (*GetUserFriendsRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_user_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserFriendsRequest) GetUserId() *common.UUID {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *GetUserFriendsRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetUserFriendsRequest) GetStatusFilter() FriendshipStatus {
	if x != nil {
		return x.StatusFilter
	}
	return FriendshipStatus_UNKNOWN
}

type GetUserFriendsResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Friends       []*Friend                  `protobuf:"bytes,1,rep,name=friends,proto3" json:"friends,omitempty"`
	Pagination    *common.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserFriendsResponse) Reset() {
	*x = GetUserFriendsResponse{}
	mi := &file_proto_user_user_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserFriendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserFriendsResponse) ProtoMessage() {}

func (x *GetUserFriendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserFriendsResponse.ProtoReflect.Descriptor instead.
func (*GetUserFriendsResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_user_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserFriendsResponse) GetFriends() []*Friend {
	if x != nil {
		return x.Friends
	}
	return nil
}

func (x *GetUserFriendsResponse) GetPagination() *common.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetUsersBatchRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UserIds              []*common.UUID         `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	IncludePrivateFields bool                   `protobuf:"varint,2,opt,name=include_private_fields,json=includePrivateFields,proto3" json:"include_private_fields,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetUsersBatchRequest) Reset() {
	*x = GetUsersBatchRequest{}
	mi := &file_proto_user_user_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersBatchRequest) ProtoMessage() {}

func (x *GetUsersBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersBatchRequest.ProtoReflect.Descriptor instead.
func (*GetUsersBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_user_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetUsersBatchRequest) GetUserIds() []*common.UUID {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *GetUsersBatchRequest) GetIncludePrivateFields() bool {
	if x != nil {
		return x.IncludePrivateFields
	}
	return false
}

type GetUsersBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserProfile         `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	NotFound      []*common.UUID         `protobuf:"bytes,2,rep,name=not_found,json=notFound,proto3" json:"not_found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersBatchResponse) Reset() {
	*x = GetUsersBatchResponse{}
	mi := &file_proto_user_user_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersBatchResponse) ProtoMessage() {}

func (x *GetUsersBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersBatchResponse.ProtoReflect.Descriptor instead.
func (*GetUsersBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_user_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetUsersBatchResponse) GetUsers() []*UserProfile {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *GetUsersBatchResponse) GetNotFound() []*common.UUID {
	if x != nil {
		return x.NotFound
	}
	return nil
}

type UpdateUserProfileRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          *common.UUID           `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Bio             string                 `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
	Interests       []string               `protobuf:"bytes,3,rep,name=interests,proto3" json:"interests,omitempty"`
	Profession      string                 `protobuf:"bytes,4,opt,name=profession,proto3" json:"profession,omitempty"`
	Skills          []string               `protobuf:"bytes,5,rep,name=skills,proto3" json:"skills,omitempty"`
	Location        string                 `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	PrivacySettings *PrivacySettings       `protobuf:"bytes,7,opt,name=privacy_settings,json=privacySettings,proto3" json:"privacy_settings,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateUserProfileRequest) Reset() {
	*x = UpdateUserProfileRequest{}
	mi := &file_proto_user_user_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserProfileRequest) ProtoMessage() {}

func (x *UpdateUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_user_service_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateUserProfileRequest) GetUserId() *common.UUID {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *UpdateUserProfileRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UpdateUserProfileRequest) GetInterests() []string {
	if x != nil {
		return x.Interests
	}
	return nil
}

func (x *UpdateUserProfileRequest) GetProfession() string {
	if x != nil {
		return x.Profession
	}
	return ""
}

func (x *UpdateUserProfileRequest) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *UpdateUserProfileRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UpdateUserProfileRequest) GetPrivacySettings() *PrivacySettings {
	if x != nil {
		return x.PrivacySettings
	}
	return nil
}

type UpdateUserProfileResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	User          *UserProfile            `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Result        *common.SuccessResponse `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserProfileResponse) Reset() {
	*x = UpdateUserProfileResponse{}
	mi := &file_proto_user_user_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserProfileResponse) ProtoMessage() {}

func (x *UpdateUserProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_user_service_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateUserProfileResponse) GetUser() *UserProfile {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UpdateUserProfileResponse) GetResult() *common.SuccessResponse {
	if x != nil {
		return x.Result
	}
	return nil
}

type CheckFriendshipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *common.UUID           `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetUserId  *common.UUID           `protobuf:"bytes,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckFriendshipRequest) Reset() {
	*x = CheckFriendshipRequest{}
	mi := &file_proto_user_user_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckFriendshipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFriendshipRequest) ProtoMessage() {}

func (x *CheckFriendshipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFriendshipRequest.ProtoReflect.Descriptor instead.
func (*CheckFriendshipRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_user_service_proto_rawDescGZIP(), []int{11}
}

func (x *CheckFriendshipRequest) GetUserId() *common.UUID {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *CheckFriendshipRequest) GetTargetUserId() *common.UUID {
	if x != nil {
		return x.TargetUserId
	}
	return nil
}

type CheckFriendshipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        FriendshipStatus       `protobuf:"varint,1,opt,name=status,proto3,enum=user.FriendshipStatus" json:"status,omitempty"`
	FriendsSince  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=friends_since,json=friendsSince,proto3" json:"friends_since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckFriendshipResponse) Reset() {
	*x = CheckFriendshipResponse{}
	mi := &file_proto_user_user_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckFriendshipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFriendshipResponse) ProtoMessage() {}

func (x *CheckFriendshipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFriendshipResponse.ProtoReflect.Descriptor instead.
func (*CheckFriendshipResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_user_service_proto_rawDescGZIP(), []int{12}
}

func (x *CheckFriendshipResponse) GetStatus() FriendshipStatus {
	if x != nil {
		return x.Status
	}
	return FriendshipStatus_UNKNOWN
}

func (x *CheckFriendshipResponse) GetFriendsSince() *timestamppb.Timestamp {
	if x != nil {
		return x.FriendsSince
	}
	return nil
}

type GetUserPreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *common.UUID           `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPreferencesRequest) Reset() {
	*x = GetUserPreferencesRequest{}
	mi := &file_proto_user_user_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPreferencesRequest) ProtoMessage() {}

func (x *GetUserPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPreferencesRequest.ProtoReflect.Descriptor instead.
func (*GetUserPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_user_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserPreferencesRequest) GetUserId() *common.UUID {
	if x != nil {
		return x.UserId
	}
	return nil
}

type GetUserPreferencesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Preferences   map[string]string      `protobuf:"bytes,1,rep,name=preferences,proto3" json:"preferences,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPreferencesResponse) Reset() {
	*x = GetUserPreferencesResponse{}
	mi := &file_proto_user_user_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPreferencesResponse) ProtoMessage() {}

func (x *GetUserPreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPreferencesResponse.ProtoReflect.Descriptor instead.
func (*GetUserPreferencesResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_user_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetUserPreferencesResponse) GetPreferences() map[string]string {
	if x != nil {
		return x.Preferences
	}
	return nil
}

var File_proto_user_user_service_proto protoreflect.FileDescriptor

const file_proto_user_user_service_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/user/user_service.proto\x12\x04user\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18proto/common/types.proto\"\xf2\x04\n" +
	"\vUserProfile\x12\x1c\n" +
	"\x02id\x18\x01 \x01(\v2\f.common.UUIDR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\x12\x10\n" +
	"\x03bio\x18\x06 \x01(\tR\x03bio\x12\x1c\n" +
	"\tinterests\x18\a \x03(\tR\tinterests\x12\x1e\n" +
	"\n" +
	"profession\x18\b \x01(\tR\n" +
	"profession\x12\x16\n" +
	"\x06skills\x18\t \x03(\tR\x06skills\x12\x1a\n" +
	"\blocation\x18\n" +
	" \x01(\tR\blocation\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\v \x01(\tR\tavatarUrl\x12>\n" +
	"\rdate_of_birth\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\vdateOfBirth\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vis_verified\x18\x0f \x01(\bR\n" +
	"isVerified\x12\x1b\n" +
	"\tis_active\x18\x10 \x01(\bR\bisActive\x12@\n" +
	"\x10privacy_settings\x18\x11 \x01(\v2\x15.user.PrivacySettingsR\x0fprivacySettings\"\xdc\x01\n" +
	"\x0fPrivacySettings\x12'\n" +
	"\x0fprofile_visible\x18\x01 \x01(\bR\x0eprofileVisible\x12#\n" +
	"\rshow_location\x18\x02 \x01(\bR\fshowLocation\x12\x19\n" +
	"\bshow_age\x18\x03 \x01(\bR\ashowAge\x122\n" +
	"\x15allow_friend_requests\x18\x04 \x01(\bR\x13allowFriendRequests\x12,\n" +
	"\x12show_online_status\x18\x05 \x01(\bR\x10showOnlineStatus\"\xa0\x02\n" +
	"\x06Friend\x12\x1c\n" +
	"\x02id\x18\x01 \x01(\v2\f.common.UUIDR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x10\n" +
	"\x03bio\x18\x05 \x01(\tR\x03bio\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x06 \x01(\tR\tavatarUrl\x12.\n" +
	"\x06status\x18\a \x01(\x0e2\x16.user.FriendshipStatusR\x06status\x12?\n" +
	"\rfriends_since\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\ffriendsSince\"t\n" +
	"\x15GetUserProfileRequest\x12%\n" +
	"\auser_id\x18\x01 \x01(\v2\f.common.UUIDR\x06userId\x124\n" +
	"\x16include_private_fields\x18\x02 \x01(\bR\x14includePrivateFields\"?\n" +
	"\x16GetUserProfileResponse\x12%\n" +
	"\x04user\x18\x01 \x01(\v2\x11.user.UserProfileR\x04user\"\xb6\x01\n" +
	"\x15GetUserFriendsRequest\x12%\n" +
	"\auser_id\x18\x01 \x01(\v2\f.common.UUIDR\x06userId\x129\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x19.common.PaginationRequestR\n" +
	"pagination\x12;\n" +
	"\rstatus_filter\x18\x03 \x01(\x0e2\x16.user.FriendshipStatusR\fstatusFilter\"|\n" +
	"\x16GetUserFriendsResponse\x12&\n" +
	"\afriends\x18\x01 \x03(\v2\f.user.FriendR\afriends\x12:\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1a.common.PaginationResponseR\n" +
	"pagination\"u\n" +
	"\x14GetUsersBatchRequest\x12'\n" +
	"\buser_ids\x18\x01 \x03(\v2\f.common.UUIDR\auserIds\x124\n" +
	"\x16include_private_fields\x18\x02 \x01(\bR\x14includePrivateFields\"k\n" +
	"\x15GetUsersBatchResponse\x12'\n" +
	"\x05users\x18\x01 \x03(\v2\x11.user.UserProfileR\x05users\x12)\n" +
	"\tnot_found\x18\x02 \x03(\v2\f.common.UUIDR\bnotFound\"\x87\x02\n" +
	"\x18UpdateUserProfileRequest\x12%\n" +
	"\auser_id\x18\x01 \x01(\v2\f.common.UUIDR\x06userId\x12\x10\n" +
	"\x03bio\x18\x02 \x01(\tR\x03bio\x12\x1c\n" +
	"\tinterests\x18\x03 \x03(\tR\tinterests\x12\x1e\n" +
	"\n" +
	"profession\x18\x04 \x01(\tR\n" +
	"profession\x12\x16\n" +
	"\x06skills\x18\x05 \x03(\tR\x06skills\x12\x1a\n" +
	"\blocation\x18\x06 \x01(\tR\blocation\x12@\n" +
	"\x10privacy_settings\x18\a \x01(\v2\x15.user.PrivacySettingsR\x0fprivacySettings\"s\n" +
	"\x19UpdateUserProfileResponse\x12%\n" +
	"\x04user\x18\x01 \x01(\v2\x11.user.UserProfileR\x04user\x12/\n" +
	"\x06result\x18\x02 \x01(\v2\x17.common.SuccessResponseR\x06result\"s\n" +
	"\x16CheckFriendshipRequest\x12%\n" +
	"\auser_id\x18\x01 \x01(\v2\f.common.UUIDR\x06userId\x122\n" +
	"\x0etarget_user_id\x18\x02 \x01(\v2\f.common.UUIDR\ftargetUserId\"\x8a\x01\n" +
	"\x17CheckFriendshipResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\x0e2\x16.user.FriendshipStatusR\x06status\x12?\n" +
	"\rfriends_since\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ffriendsSince\"B\n" +
	"\x19GetUserPreferencesRequest\x12%\n" +
	"\auser_id\x18\x01 \x01(\v2\f.common.UUIDR\x06userId\"\xb1\x01\n" +
	"\x1aGetUserPreferencesResponse\x12S\n" +
	"\vpreferences\x18\x01 \x03(\v21.user.GetUserPreferencesResponse.PreferencesEntryR\vpreferences\x1a>\n" +
	"\x10PreferencesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*G\n" +
	"\x10FriendshipStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\f\n" +
	"\bACCEPTED\x10\x02\x12\v\n" +
	"\aBLOCKED\x10\x032\xb3\x04\n" +
	"\vUserService\x12K\n" +
	"\x0eGetUserProfile\x12\x1b.user.GetUserProfileRequest\x1a\x1c.user.GetUserProfileResponse\x12K\n" +
	"\x0eGetUserFriends\x12\x1b.user.GetUserFriendsRequest\x1a\x1c.user.GetUserFriendsResponse\x12H\n" +
	"\rGetUsersBatch\x12\x1a.user.GetUsersBatchRequest\x1a\x1b.user.GetUsersBatchResponse\x12T\n" +
	"\x11UpdateUserProfile\x12\x1e.user.UpdateUserProfileRequest\x1a\x1f.user.UpdateUserProfileResponse\x12N\n" +
	"\x0fCheckFriendship\x12\x1c.user.CheckFriendshipRequest\x1a\x1d.user.CheckFriendshipResponse\x12W\n" +
	"\x12GetUserPreferences\x12\x1f.user.GetUserPreferencesRequest\x1a .user.GetUserPreferencesResponse\x12A\n" +
	"\x06Health\x12\x1a.common.HealthCheckRequest\x1a\x1b.common.HealthCheckResponseB(Z&github.com/link-app/backend/proto/userb\x06proto3"

var (
	file_proto_user_user_service_proto_rawDescOnce sync.Once
	file_proto_user_user_service_proto_rawDescData []byte
)

func file_proto_user_user_service_proto_rawDescGZIP() []byte {
	file_proto_user_user_service_proto_rawDescOnce.Do(func() {
		file_proto_user_user_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_user_service_proto_rawDesc), len(file_proto_user_user_service_proto_rawDesc)))
	})
	return file_proto_user_user_service_proto_rawDescData
}

var file_proto_user_user_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_user_user_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_user_user_service_proto_goTypes = []any{
	(FriendshipStatus)(0),              // 0: user.FriendshipStatus
	(*UserProfile)(nil),                // 1: user.UserProfile
	(*PrivacySettings)(nil),            // 2: user.PrivacySettings
	(*Friend)(nil),                     // 3: user.Friend
	(*GetUserProfileRequest)(nil),      // 4: user.GetUserProfileRequest
	(*GetUserProfileResponse)(nil),     // 5: user.GetUserProfileResponse
	(*GetUserFriendsRequest)(nil),      // 6: user.GetUserFriendsRequest
	(*GetUserFriendsResponse)(nil),     // 7: user.GetUserFriendsResponse
	(*GetUsersBatchRequest)(nil),       // 8: user.GetUsersBatchRequest
	(*GetUsersBatchResponse)(nil),      // 9: user.GetUsersBatchResponse
	(*UpdateUserProfileRequest)(nil),   // 10: user.UpdateUserProfileRequest
	(*UpdateUserProfileResponse)(nil),  // 11: user.UpdateUserProfileResponse
	(*CheckFriendshipRequest)(nil),     // 12: user.CheckFriendshipRequest
	(*CheckFriendshipResponse)(nil),    // 13: user.CheckFriendshipResponse
	(*GetUserPreferencesRequest)(nil),  // 14: user.GetUserPreferencesRequest
	(*GetUserPreferencesResponse)(nil), // 15: user.GetUserPreferencesResponse
	nil,                                // 16: user.GetUserPreferencesResponse.PreferencesEntry
	(*common.UUID)(nil),                // 17: common.UUID
	(*timestamppb.Timestamp)(nil),      // 18: google.protobuf.Timestamp
	(*common.PaginationRequest)(nil),   // 19: common.PaginationRequest
	(*common.PaginationResponse)(nil),  // 20: common.PaginationResponse
	(*common.SuccessResponse)(nil),     // 21: common.SuccessResponse
	(*common.HealthCheckRequest)(nil),  // 22: common.HealthCheckRequest
	(*common.HealthCheckResponse)(nil), // 23: common.HealthCheckResponse
}
var file_proto_user_user_service_proto_depIdxs = []int32{
	17, // 0: user.UserProfile.id:type_name -> common.UUID
	18, // 1: user.UserProfile.date_of_birth:type_name -> google.protobuf.Timestamp
	18, // 2: user.UserProfile.created_at:type_name -> google.protobuf.Timestamp
	18, // 3: user.UserProfile.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 4: user.UserProfile.privacy_settings:type_name -> user.PrivacySettings
	17, // 5: user.Friend.id:type_name -> common.UUID
	0,  // 6: user.Friend.status:type_name -> user.FriendshipStatus
	18, // 7: user.Friend.friends_since:type_name -> google.protobuf.Timestamp
	17, // 8: user.GetUserProfileRequest.user_id:type_name -> common.UUID
	1,  // 9: user.GetUserProfileResponse.user:type_name -> user.UserProfile
	17, // 10: user.GetUserFriendsRequest.user_id:type_name -> common.UUID
	19, // 11: user.GetUserFriendsRequest.pagination:type_name -> common.PaginationRequest
	0,  // 12: user.GetUserFriendsRequest.status_filter:type_name -> user.FriendshipStatus
	3,  // 13: user.GetUserFriendsResponse.friends:type_name -> user.Friend
	20, // 14: user.GetUserFriendsResponse.pagination:type_name -> common.PaginationResponse
	17, // 15: user.GetUsersBatchRequest.user_ids:type_name -> common.UUID
	1,  // 16: user.GetUsersBatchResponse.users:type_name -> user.UserProfile
	17, // 17: user.GetUsersBatchResponse.not_found:type_name -> common.UUID
	17, // 18: user.UpdateUserProfileRequest.user_id:type_name -> common.UUID
	2,  // 19: user.UpdateUserProfileRequest.privacy_settings:type_name -> user.PrivacySettings
	1,  // 20: user.UpdateUserProfileResponse.user:type_name -> user.UserProfile
	21, // 21: user.UpdateUserProfileResponse.result:type_name -> common.SuccessResponse
	17, // 22: user.CheckFriendshipRequest.user_id:type_name -> common.UUID
	17, // 23: user.CheckFriendshipRequest.target_user_id:type_name -> common.UUID
	0,  // 24: user.CheckFriendshipResponse.status:type_name -> user.FriendshipStatus
	18, // 25: user.CheckFriendshipResponse.friends_since:type_name -> google.protobuf.Timestamp
	17, // 26: user.GetUserPreferencesRequest.user_id:type_name -> common.UUID
	16, // 27: user.GetUserPreferencesResponse.preferences:type_name -> user.GetUserPreferencesResponse.PreferencesEntry
	4,  // 28: user.UserService.GetUserProfile:input_type -> user.GetUserProfileRequest
	6,  // 29: user.UserService.GetUserFriends:input_type -> user.GetUserFriendsRequest
	8,  // 30: user.UserService.GetUsersBatch:input_type -> user.GetUsersBatchRequest
	10, // 31: user.UserService.UpdateUserProfile:input_type -> user.UpdateUserProfileRequest
	12, // 32: user.UserService.CheckFriendship:input_type -> user.CheckFriendshipRequest
	14, // 33: user.UserService.GetUserPreferences:input_type -> user.GetUserPreferencesRequest
	22, // 34: user.UserService.Health:input_type -> common.HealthCheckRequest
	5,  // 35: user.UserService.GetUserProfile:output_type -> user.GetUserProfileResponse
	7,  // 36: user.UserService.GetUserFriends:output_type -> user.GetUserFriendsResponse
	9,  // 37: user.UserService.GetUsersBatch:output_type -> user.GetUsersBatchResponse
	11, // 38: user.UserService.UpdateUserProfile:output_type -> user.UpdateUserProfileResponse
	13, // 39: user.UserService.CheckFriendship:output_type -> user.CheckFriendshipResponse
	15, // 40: user.UserService.GetUserPreferences:output_type -> user.GetUserPreferencesResponse
	23, // 41: user.UserService.Health:output_type -> common.HealthCheckResponse
	35, // [35:42] is the sub-list for method output_type
	28, // [28:35] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_proto_user_user_service_proto_init() }
func file_proto_user_user_service_proto_init() {
	if File_proto_user_user_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_user_service_proto_rawDesc), len(file_proto_user_user_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_user_service_proto_goTypes,
		DependencyIndexes: file_proto_user_user_service_proto_depIdxs,
		EnumInfos:         file_proto_user_user_service_proto_enumTypes,
		MessageInfos:      file_proto_user_user_service_proto_msgTypes,
	}.Build()
	File_proto_user_user_service_proto = out.File
	file_proto_user_user_service_proto_goTypes = nil
	file_proto_user_user_service_proto_depIdxs = nil
}
