# Loki Configuration for Standard Profile  
# Balanced resource usage with 3-day retention
# Good performance while controlling costs

auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

# Balanced caching for good performance
query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 75  # Balanced caching
        ttl: 24h

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

# Standard retention policy
limits_config:
  retention_period: 72h      # 3 days retention
  ingestion_rate_mb: 8       # Standard rate
  ingestion_burst_size_mb: 12
  max_concurrent_tail_requests: 10
  max_query_parallelism: 32
  max_streams_per_user: 10000

# Standard compactor settings
compactor:
  working_directory: /loki/compactor  
  shared_store: filesystem
  compaction_interval: 5m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150

# Enable ruler for alerting
ruler:
  enable_api: true
  alertmanager_url: http://alertmanager:9093
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules
  ring:
    kvstore:
      store: inmemory

# Disable analytics
analytics:
  reporting_enabled: false

# Memberlist config
memberlist:
  abort_if_cluster_join_fails: false
  bind_port: 7946
  join_members:
  - loki:7946