version: '3.8'

# Docker Compose override for database isolation
# Generated by Terraform service-databases module

services:
%{ for service, config in services ~}
  ${service}-service:
    environment:
      - DB_HOST=${config.DB_HOST}
      - DB_PORT=${config.DB_PORT}
      - DB_NAME=${config.DB_NAME}
      - DB_USER=${config.DB_USER}
      - DB_PASSWORD=${config.DB_PASSWORD}
      - DB_SSLMODE=${config.DB_SSLMODE}

%{ endfor ~}
